name: PNPM v7
on: push
jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.21.3'

      - run: npm install -g pnpm@7

      - run: pnpm install --prod
